### ISSUE TITLE
[Exploration] CRUD/backend framework  options

### ISSUE THREAD

**Issue by madcampos** [torontojs/vms#27]
We want to explorer what options we have for backend frameworks to use on the VMS.

So far Hono is the main contender.

## Tasks
- [x] Explorer creating a CRUD with Hono
- [x] Compare Hono to Express
- [x] Explore other alternatives
- [x] Compare how maintainable those tools are

**Comment by kbventures** [comment]
Hono is lightweight, minimalist, and TypeScript-first. It’s well-suited for serverless environments, providing flexibility and cost-efficiency (not important for this project). It integrates well with Cloudflare, D1 (SQLite-like), and KV, with the free tier covering all three services. If we ever wanted to port the code to Express, this would be easy due to similar patterns for routes, middleware, and HTTP methods. Hono also follows web standards, ensuring compatibility and maintainability.
