### ISSUE TITLE
[Exploration] Testing tools options

### ISSUE THREAD

**Issue by madcampos** [torontojs/vms#28]
We want to explore what options for backend/API testing tools we have available.

So far the options are: **Postman** and **curl**.

## Tasks
- [x] Find API testing tools alternatives
- [x] Find tools to automate test generation
- [x] Check API doc tools like swagger and alternatives
- [x] Compare how easy it is to share resources like requests, test, etc.

**Comment by Zen-cronic** [comment]
An open-source contender to postman/insomnia: [Bruno](https://github.com/usebruno/bruno)

**Comment by kbventures** [comment]
@Zen-cronic 
Bruno creates plain-text API files with version control using Git it future-proof and easier to port
